#
###Version, do not change!##
#Range: > 0
Version = 7

#Workers Config Client Side:
[WorkersClientSide]
	#
	#----CommandScreenToggle----
	#	(takes effect after restart)
	#	
	#Should the key to open the command screen be toggled instead of held?""
	#default: false
	CommandScreenToggle = false
	#
	#----Should Workers Make Villager Huh? sound?----
	#	(takes effect after restart)
	#	default: true
	PlayVillagerAmbientSound = true
	#
	#----Should Workers look like Villagers?----
	#	(takes effect after restart)
	#	default: true
	WorkersLookLikeVillagers = true

#Workers Config:
[Workers]
	#
	#The amount of currency required to hire a farmer.
	#	(takes effect after restart)
	#	default: 11
	#Range: 0 ~ 999
	FarmerCost = 11
	#
	#RecruitsPayment
	#	(takes effect after restart)
	#	
	#Should workers need to be payed in intervals?
	#default: false
	WorkersPayment = false
	#
	#----Currency----
	#	(takes effect after restart)
	#	The Item defined here, will be used to hire workers. For example: ["minecraft:diamond"]	default: ["minecraft:emerald"]
	WorkersCurrency = "minecraft:emerald"
	#
	#RecruitsPaymentAmount
	#	(takes effect after restart)
	#	
	#The amount of currency workers need to be payed?
	#default: 1
	#Range: 1 ~ 1453
	WorkersPaymentAmount = 1
	#
	#The amount of currency required to hire a fisherman.
	#	(takes effect after restart)
	#	default: 25
	#Range: 0 ~ 999
	FishermanCost = 25
	#
	#----WorkerChunkLoading----
	#	(takes effect after restart)
	#	
	#Should workers load the chunk they are in?""
	#default: true
	WorkerChunkLoading = true
	#
	#Should Pillagers attack Workers?
	#	(takes effect after restart)
	#	default: true
	PillagerAttackWorkers = true
	#
	#The amount of currency required to hire a chicken farmer.
	#	(takes effect after restart)
	#	default: 15
	#Range: 0 ~ 999
	ChickenFarmerCost = 15
	#
	#The amount of currency required to hire a cattle farmer.
	#	(takes effect after restart)
	#	default: 15
	#Range: 0 ~ 999
	CattleFarmerCost = 18
	#
	#RecruitsPaymentInterval
	#	(takes effect after restart)
	#	
	#The interval in minutes workers need to be payed?
	#default: 15
	#Range: 1 ~ 1453
	WorkersPaymentInterval = 15
	#
	#The amount of currency required to hire a miner.
	#	(takes effect after restart)
	#	default: 20
	#Range: 0 ~ 999
	MinerCost = 20
	#
	#RecruitsNoPaymentAction
	#	(takes effect after restart)
	#	
	#The action the workers will do when they don't get payed.
	#default: DISBAND
	#Allowed Values: DISBAND, DESPAWN
	WorkersNoPaymentAction = "DISBAND"
	#
	#Should Hostile Mobs attack Workers?
	#	(takes effect after restart)
	#	default: true
	MonsterAttackWorkers = true
	#
	#The amount of currency required to hire a merchant.
	#	(takes effect after restart)
	#	default: 12
	#Range: 0 ~ 999
	MerchantCost = 12
	#
	#The amount of currency required to hire a shepherd.
	#	(takes effect after restart)
	#	default: 10
	#Range: 0 ~ 999
	ShepherdCost = 16
	#
	#The amount of currency required to hire a swineherd.
	#	(takes effect after restart)
	#	default: 10
	#Range: 0 ~ 999
	SwineherdCost = 19
	#
	#Should Owners receive info's about the worker through text?
	#	(takes effect after restart)
	#	default: true
	OwnerReceiveInfo = true
	#
	#The amount of currency required to hire a lumberjack.
	#	(takes effect after restart)
	#	default: 14
	#Range: 0 ~ 999
	LumberjackCost = 14

#Recruit Village Config:
[Villages]
	#
	#----Should Villager Workers that were created with Tables release the POI for other Villagers?----
	#----True -> allows multiple villagers to become a worker with one table.----
	#----False -> only one villager can become a recruit with one table.----
	#	(takes effect after restart)
	#	default: true
	WorkersTablesPOIReleasing = false
	#
	#----Should the profession tables drop when breaking?----
	#	(takes effect after restart)
	#	default: true
	ProfessionBlocksDrop = true

